name: CD

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
            
    - name: Pull Changes
      run: git pull origin main
      working-directory: /home/adminuser/munsoc/munsoc-backend

    - name: Build and Deploy
      run: |
        docker compose up --build -d
      working-directory: /home/adminuser/munsoc/munsoc-backend